# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-06-10 14:54-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: pinakes/common/exception_handler.py:27
msgid "Internal Error"
msgstr "Error interno"

#: pinakes/common/exception_handler.py:31
msgid "{}. Report to the support team if it is not an user error."
msgstr "{}. Informe al equipo de soporte si no es un error del usuario."

#: pinakes/common/exception_handler.py:37
msgid "Unauthorized"
msgstr "No autorizado"

#: pinakes/common/image_mixin.py:43
msgid "{} object has no attribute 'icon'."
msgstr "El objeto de {} no tiene el atributo 'icon'."

#: pinakes/common/image_mixin.py:69
msgid "Icon attribute has been set on {} object (id: {})."
msgstr "El atributo icono se estableció en el objeto de {} (id: {})."

#: pinakes/common/image_mixin.py:95 pinakes/common/image_mixin.py:123
msgid "Icon attribute has not been set on {} object (id: {})."
msgstr "El atributo icono no se estableció en el objeto de {} (id: {})."

#: pinakes/common/models/fields.py:14
msgid "An encrypted JSON object"
msgstr "Un objeto JSON encriptado"

#: pinakes/main/analytics/analytics_collectors.py:23
msgid "General platform configuration."
msgstr "Configuración general de la plataforma."

#: pinakes/main/analytics/analytics_collectors.py:64
msgid "Data on sources"
msgstr "Datos sobre las fuentes"

#: pinakes/main/analytics/analytics_collectors.py:89
msgid "Data on service_offerings"
msgstr "Datos sobre ofertas de servicios"

#: pinakes/main/analytics/analytics_collectors.py:119
msgid "Data on service_offering_nodes"
msgstr "Datos sobre service_offering_nodes"

#: pinakes/main/analytics/analytics_collectors.py:150
msgid "Data on service_instances"
msgstr "Datos sobre service_instances"

#: pinakes/main/analytics/analytics_collectors.py:180
msgid "Data on service_inventories"
msgstr "Datos sobre los inventarios de servicios"

#: pinakes/main/analytics/analytics_collectors.py:209
msgid "Data on portfolios"
msgstr "Datos sobre las carteras"

#: pinakes/main/analytics/analytics_collectors.py:236
msgid "Data on portfolio_items"
msgstr "Datos sobre portfolio_items"

#: pinakes/main/analytics/analytics_collectors.py:267
msgid "Data on orders"
msgstr "Datos sobre los pedidos"

#: pinakes/main/analytics/analytics_collectors.py:294
msgid "Data on order_items"
msgstr "Datos sobre order_items"

#: pinakes/main/analytics/analytics_collectors.py:328
msgid "Data on approval_requests"
msgstr "Datos sobre approval_requests"

#: pinakes/main/analytics/analytics_collectors.py:355
msgid "Data on service_plans"
msgstr "Data on service_plans"

#: pinakes/main/analytics/analytics_collectors.py:383
msgid "Data on templates"
msgstr "Datos sobre las plantillas de tareas"

#: pinakes/main/analytics/analytics_collectors.py:407
msgid "Data on workflows"
msgstr "Datos sobre los flujos de trabajo"

#: pinakes/main/analytics/analytics_collectors.py:434
msgid "Data on requests"
msgstr "Datos sobre las solicitudes"

#: pinakes/main/analytics/analytics_collectors.py:469
msgid "Data on actions"
msgstr "Datos sobre las acciones"

#: pinakes/main/analytics/analytics_collectors.py:495
msgid "Data on tag_links"
msgstr "Datos sobre tag_links"

#: pinakes/main/analytics/analytics_collectors.py:522
msgid "Data on groups"
msgstr "Datos sobre los grupos"

#: pinakes/main/analytics/analytics_collectors.py:544
msgid "Counts of orders by products"
msgstr "Recuento de pedidos por productos"

#: pinakes/main/analytics/analytics_collectors.py:581
msgid "Counts of tags by portfolios"
msgstr "Recuento de etiquetas por carteras"

#: pinakes/main/analytics/analytics_collectors.py:615
msgid "Counts of tags by products"
msgstr "Recuento de etiquetas por productos"

#: pinakes/main/analytics/analytics_collectors.py:649
msgid "Counts of tags by service_intentories"
msgstr "Recuento de etiquetas por servicio_intensidades"

#: pinakes/main/analytics/analytics_collectors.py:683
msgid "Order data by product"
msgstr "Datos del pedido por producto"

#: pinakes/main/analytics/analytics_collectors.py:783
msgid "Approval request time spent by group"
msgstr "Tiempo de solicitud de aprobación por grupo"

#: pinakes/main/approval/exceptions.py:8
msgid "Insufficient query parameters"
msgstr "Parámetros de consulta insuficientes"

#: pinakes/main/approval/exceptions.py:13
msgid "Invalid State Transition"
msgstr "Transición de estado no válida"

#: pinakes/main/approval/exceptions.py:18
msgid "Field cannot be blank"
msgstr "El campo no puede estar en blanco"

#: pinakes/main/approval/exceptions.py:23
msgid "Duplicated UUID for approver groups"
msgstr "UUID duplicada para grupos de aprobadores"

#: pinakes/main/approval/exceptions.py:28
msgid "Group has no approver role"
msgstr "El grupo no tiene rol de aprobador"

#: pinakes/main/approval/exceptions.py:33
msgid "Group does not exist"
msgstr "El grupo no existe"

#: pinakes/main/approval/services/create_action.py:49
msgid "The memo message cannot be blank"
msgstr "El mensaje del memorándum no puede estar en blanco"

#: pinakes/main/approval/services/create_action.py:56
msgid "Current request is not pending state"
msgstr "La solicitud actual no está en estado pendiente"

#: pinakes/main/approval/services/create_action.py:64
msgid "Current request is not started state"
msgstr "La solicitud actual no está en estado iniciado"

#: pinakes/main/approval/services/create_action.py:72
msgid "Current request is not in pending state"
msgstr "La solicitud actual no está en estado pendiente"

#: pinakes/main/approval/services/create_action.py:80
#: pinakes/main/approval/services/create_action.py:97
msgid "Current request is not in notified state"
msgstr "La solicitud actual no está en estado notificado"

#: pinakes/main/approval/services/create_action.py:85
msgid "Only child level request can be approved"
msgstr "Solo puede aprobarse la solicitud de nivel secundario"

#: pinakes/main/approval/services/create_action.py:102
msgid "Only child level request can be denied"
msgstr "Solo puede denegarse la solicitud de nivel secundario"

#: pinakes/main/approval/services/create_action.py:107
msgid "A reason has to be provided if a request is being denied"
msgstr "Debe proporcionarse un motivo si se deniega una solicitud"

#: pinakes/main/approval/services/create_action.py:119
msgid "Only root level request can be canceled"
msgstr "Solo puede cancelarse una solicitud de nivel raíz"

#: pinakes/main/approval/services/create_action.py:124
msgid "The request has already finished"
msgstr "La solicitud ya ha finalizado"

#: pinakes/main/approval/services/create_action.py:136
msgid "Current request has already finished"
msgstr "La solicitud actual ya ha finalizado"

#: pinakes/main/approval/services/create_action.py:140
msgid "Failure reason is missing"
msgstr "Falta el motivo de la falla"

#: pinakes/main/approval/services/create_action.py:144
msgid "Only child level request can be flagged error"
msgstr "Solo puede marcar con error la solicitud de nivel secundario"

#: pinakes/main/approval/services/email_notification.py:91
msgid "Failed to email group {}"
msgstr "Error al enviar correo electrónico al grupo {}"

#: pinakes/main/approval/services/update_request.py:19
msgid "Auto-approved"
msgstr "Aprobado automáticamente"

#: pinakes/main/approval/validations.py:56
msgid "Group id {} does not exist"
msgstr "El Id. de grupo {} no existe"

#: pinakes/main/approval/validations.py:64
msgid "Group {} does not have approver role"
msgstr "El grupo {} no tiene rol de aprobador"

#: pinakes/main/approval/views.py:188
msgid "Insufficient resource object params: {}"
msgstr "Parámetros de objeto de recurso insuficientes: {}"

#: pinakes/main/catalog/exceptions.py:8
msgid "Bad query parameters"
msgstr "Parámetros de consulta incorrectos"

#: pinakes/main/catalog/exceptions.py:13
msgid "Invalid survey"
msgstr "Encuesta no válida"

#: pinakes/main/catalog/exceptions.py:18
msgid "Uncancelable Order"
msgstr "Orden no cancelable"

#: pinakes/main/catalog/models.py:190
msgid "Info"
msgstr "Información"

#: pinakes/main/catalog/models.py:191
msgid "Error"
msgstr "Error"

#: pinakes/main/catalog/models.py:192
msgid "Warning"
msgstr "Advertencia"

#: pinakes/main/catalog/models.py:193
msgid "Debug"
msgstr "Debug"

#: pinakes/main/catalog/models.py:332 pinakes/main/catalog/models.py:419
msgid "Approval Pending"
msgstr "Aprobación pendiente"

#: pinakes/main/catalog/models.py:333 pinakes/main/catalog/models.py:420
msgid "Approved"
msgstr "Aprobado"

#: pinakes/main/catalog/models.py:334 pinakes/main/catalog/models.py:421
msgid "Canceled"
msgstr "Cancelado"

#: pinakes/main/catalog/models.py:335 pinakes/main/catalog/models.py:422
msgid "Completed"
msgstr "Completado"

#: pinakes/main/catalog/models.py:336 pinakes/main/catalog/models.py:423
msgid "Created"
msgstr "Creado"

#: pinakes/main/catalog/models.py:337 pinakes/main/catalog/models.py:424
msgid "Denied"
msgstr "Denegado"

#: pinakes/main/catalog/models.py:338 pinakes/main/catalog/models.py:425
#: pinakes/main/models.py:67
msgid "Failed"
msgstr "Fallido"

#: pinakes/main/catalog/models.py:339 pinakes/main/catalog/models.py:426
msgid "Ordered"
msgstr "Ordenado"

#: pinakes/main/catalog/models.py:549
#, python-format
msgid ""
"Created Approval Request ref: %(approval_request_ref)s. Catalog approval "
"request id: %(approval_request_id)s"
msgstr "Se creó la referencia de solicitud de aprobación: {}. Id. de solicitud de aprobación de catálogo: {}"

#: pinakes/main/catalog/models.py:569
msgid "undecided"
msgstr "indecisos"

#: pinakes/main/catalog/models.py:570
msgid "approved"
msgstr "aprobado"

#: pinakes/main/catalog/models.py:571
msgid "canceled"
msgstr "cancelado"

#: pinakes/main/catalog/models.py:572
msgid "denied"
msgstr "denegado"

#: pinakes/main/catalog/models.py:573
msgid "failed"
msgstr "falló"

#: pinakes/main/catalog/serializers.py:407
msgid "Order"
msgstr "Pedir"

#: pinakes/main/catalog/serializers.py:408
msgid "OrderItem"
msgstr "OrderItem"

#: pinakes/main/catalog/services/cancel_order.py:61
msgid "Order {} is not cancel able in its current state: {}"
msgstr "La orden {} no se puede cancelar en su estado actual: {}"

#: pinakes/main/catalog/services/collect_tag_resources.py:62
msgid "Portfolio item {} does not have related service offering"
msgstr "El elemento de cartera {} no tiene una oferta de servicio relacionada"

#: pinakes/main/catalog/services/copy_portfolio_item.py:47
msgid "{} is not order able, and cannot be copied"
msgstr "{} no se puede pedir y no se puede copiar"

#: pinakes/main/catalog/services/finish_order.py:31
#, python-format
msgid "Order %(order_id)s has failed"
msgstr "Error en el pedido {}"

#: pinakes/main/catalog/services/finish_order.py:36
#, python-format
msgid "Order %(order_id)s is completed"
msgstr "El pedido {} está completado"

#: pinakes/main/catalog/services/finish_order.py:44
msgid "Order Canceled"
msgstr "Pedido cancelado"

#: pinakes/main/catalog/services/finish_order.py:48
msgid "Order Failed"
msgstr "Pedido fallido"

#: pinakes/main/catalog/services/finish_order.py:53
#, python-format
msgid ""
"This order item has failed due to the entire order %(state)s before it ran"
msgstr "Este elemento de pedido falló porque se ejecutó el pedido entero {} anterior"

#: pinakes/main/catalog/services/finish_order_item.py:34
#, python-format
msgid "Order Item %(id)s is completed"
msgstr "El elemento de pedido {} está completado"

#: pinakes/main/catalog/services/handle_approval_events.py:76
msgid "Internal Error. Please contact our support team."
msgstr "Error interno. Por favor, póngase en contacto con nuestro equipo de soporte."

#: pinakes/main/catalog/services/handle_approval_events.py:109
#, python-format
msgid "Approval Request finished with status %(state)s"
msgstr "La solicitud de aprobación finalizó con el estado '{}'"

#: pinakes/main/catalog/services/handle_approval_events.py:115
#, python-format
msgid "Approval Request finished with status %(state)s and reason %(reason)s"
msgstr "La solicitud de aprobación finalizó con el estado '{}' y el motivo '{}'"

#: pinakes/main/catalog/services/provision_order_item.py:30
#, python-format
msgid "Order Item %(id)s is provisioned"
msgstr "El artículo de la orden %(id)s se aprovisiona"

#: pinakes/main/catalog/services/sanitize_parameters.py:42
msgid "parameter {} is required and must have a value"
msgstr "se requiere el parámetro {} y debe tener un valor"

#: pinakes/main/catalog/services/start_order.py:21
msgid "Submitting Order for provisioning"
msgstr "Enviando elemento de pedido {} para aprovisionamiento"

#: pinakes/main/catalog/services/start_order_item.py:53
#, python-format
msgid "Submitting Order Item %(item_id)s for provisioning"
msgstr "Enviando elemento de pedido {} para aprovisionamiento"

#: pinakes/main/catalog/services/submit_approval_request.py:61
msgid "Failed to submit request to approval for Order {}, error: {}"
msgstr "No se pudo enviar la solicitud de aprobación para el pedido {}, error: {}"

#: pinakes/main/catalog/services/validate_order_item.py:45
msgid ""
"The underlying survey on product {} in the portfolio {} has been changed and "
"is no longer valid, please contact an administrator to fix it."
msgstr "La encuesta subyacente para el producto {} en la cartera {} ha cambiado y ya no es válida. Comuníquese con un administrador para corregirla."

#: pinakes/main/catalog/views.py:521
msgid "Order {} does not have related order items"
msgstr "El pedido {} no tiene elementos de pedido relacionados"

#: pinakes/main/catalog/views.py:531
#, python-format
msgid "Computed tags for order %(order_id)d: %(tag_resources)s"
msgstr "Etiquetas calculadas para el pedido {}: {}"

#: pinakes/main/inventory/exceptions.py:8
msgid "Refresh already registered"
msgstr "La actualización ya está registrada"

#: pinakes/main/inventory/serializers.py:50
#, python-format
msgid "%(name)s is unavailable, refresh skipped"
msgstr "%(name)s no está disponible, se salta la actualización"

#: pinakes/main/inventory/serializers.py:55
#, python-format
msgid "Refresh failed: %(error)s"
msgstr "La actualización ha fallado: %(error)s"

#: pinakes/main/inventory/serializers.py:59
msgid "adds"
msgstr "añade"

#: pinakes/main/inventory/serializers.py:60
msgid "deletes"
msgstr "borra"

#: pinakes/main/inventory/serializers.py:61
msgid "updates"
msgstr "actualizaciones"

#: pinakes/main/inventory/serializers.py:83
#, python-format
msgid "Service Inventories: %(stats)s;\n"
msgstr "Inventarios de servicios: %(stats)s;\n"

#: pinakes/main/inventory/serializers.py:88
#, python-format
msgid "Job Templates & Workflows: %(soi_stats)s;\n"
msgstr "Plantillas de trabajos de flujo de trabajo\n"

#: pinakes/main/inventory/serializers.py:93
#, python-format
msgid "Workflow Template Nodes: %(son_stats)s;\n"
msgstr "Plantilla de flujo de trabajo\n"

#: pinakes/main/inventory/serializers.py:97
#, python-format
msgid "Service Plan: %(sp_stats)s;\n"
msgstr "Plan de servicio: %(sp_stats)s;\n"

#: pinakes/main/inventory/serializers.py:102
msgid "Nothing to update"
msgstr "Nada que actualizar"

#: pinakes/main/inventory/serializers.py:125
#, python-format
msgid ""
"Source cannot be changed to url %(new_url)s uuid %(new_install_uuid)s, "
"currently bound to url %(url)s with uuid %(install_uuid)s"
msgstr "La fuente no puede cambiarse a la url %(new_url)s uuid %(new_install_uuid)s, actualmente vinculada a la url %(url)s con uuid %(install_uuid)s"

#: pinakes/main/inventory/serializers.py:131
#, python-format
msgid "Error: %(error)s"
msgstr "Error %(error)s - "

#: pinakes/main/inventory/services/collect_inventory_tags.py:38
msgid "ServiceOffering object {} not found"
msgstr "No se encontró el objeto ServiceOffering {}"

#: pinakes/main/inventory/services/get_service_offering.py:34
msgid "Failed to get service offering [{}]"
msgstr "No se pudo encontrar la oferta de servicio [{}]"

#: pinakes/main/inventory/task_utils/check_source_availability.py:55
msgid "Check availability completed"
msgstr "Comprobación de disponibilidad completada"

#: pinakes/main/inventory/task_utils/launch_job.py:68
#, python-format
msgid "Job %(id)s has %(status)s status"
msgstr "El trabajo %(id)s tiene el estatus de %(status)s "

#: pinakes/main/inventory/views.py:89
msgid "Refresh job {} is already {}, please try again later"
msgstr "La tarea de actualización {} ya está {}, vuelva a intentar más tarde"

#: pinakes/main/models.py:65
msgid "Done"
msgstr "Finalizado"

#: pinakes/main/models.py:66
msgid "InProgress"
msgstr "InProgress"

#: pinakes/main/models.py:68
msgid "Unknown"
msgstr "Desconocido"
